version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    expose:
      - "3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb
    networks:
      - app-network

  todo-service:
    build: ./todo-service
    expose:
      - "3002"
    environment:
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/todo-service
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build: ./frontend
    expose:
      - "3000"
    environment:
      - REACT_APP_AUTH_API_URL=/api/auth
      - REACT_APP_TODO_API_URL=/api/todos
    depends_on:
      - auth-service
      - todo-service
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - auth-service
      - todo-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 