name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies and test auth-service
        run: |
          cd auth-service
          npm install
          npm test
          
      - name: Install dependencies and test todo-service
        run: |
          cd todo-service
          npm install
          npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: taayabbb
          password: 786789786Si
          
      - name: Build and push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          push: true
          tags: taayabbb/auth-service:latest
          
      - name: Build and push todo-service
        uses: docker/build-push-action@v4
        with:
          context: ./todo-service
          push: true
          tags: taayabbb/todo-service:latest
          
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: taayabbb/frontend:latest 